version: "3.9"
services:
  library_db:
    image: postgres
    container_name: library_db
    volumes:
      - ./data/db:/var/lib/postgresql/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - GCS

  backend:
    build: 
      context: ./library_back
      dockerfile: dockerfile
    image: backend
    container_name: backend
    volumes:
      - .:/library_back/
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - GCS
    depends_on:
      - library_db

  frontend:
    build: 
      context: ./library_front
      dockerfile: dockerfile
    container_name: frontend
    volumes:
      - .:/library_front
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - GCS
    depends_on: 
      - backend

  nginx_lib:
    build:
      context: ./nginx_lib
      dockerfile: dockerfile
    image: nginx:1.22.0-alpine
    container_name: nginx
    ports:
      - 3008:3008
    volumes:
      - ./nginx:/etc/nginx.conf
    links:
      - frontend
    depends_on:
      - frontend
    networks:
      - GCS
networks:
  GCS:
    driver: bridge