version: "3.9"
services:
  library_db:
    image: postgres
    container_name: library_db
    volumes:
      - ./data/db:/var/lib/postgresql/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      GCS:
        ipv4_address: 172.30.0.2

  backend:
    image: backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /library_back/
    volumes:
      - .:/library_back/
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - GCS
    depends_on:
      - library_db
networks:
  GCS:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.1/20
         gateway: 172.30.0.1
